In [2]:
import numpy as np
import tensorflow as tf


a = tf.zeros([2, 3, 2])
c = tf.concat(a, 0)


In [4]:
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(c))




[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
