In [7]:
import numpy as np
import tensorflow as tf

a = tf.ones([4, 2,2,3])
b = tf.ones([4, 2,2,3])

c = tf.concat([a, b], 3)

print(a)
print(c)

Tensor("ones_7:0", shape=(4, 2, 2, 3), dtype=float32)
Tensor("concat_3:0", shape=(4, 2, 2, 6), dtype=float32)


In [4]:
with tf.Session() as sess:
    print(sess.run(tf.shape(a)))
    print(sess.run(b))




[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]
[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]
